Replace Urllib3 method_whitelist with allowed_methods
plamere/spotipy pull request #638
Opened 2021-02-06 15:29 UTC by ReneNulschDE

This is a proposed fix for #637 

Since Urllib3 v1.26.0 method_whitelist is deprecated and replaced with allowed_methods.

2021-02-06 15:46 UTC, stephanebruckert approved these changes

2021-02-06 16:00 UTC, stephanebruckert requested changes
Just saw that we allow requests 2.20.0
https://github.com/plamere/spotipy/blob/2.16.1/setup.py#L29

and that the minimum urllib3 requests 2.20.0 needs is <1.25 as can be seen here https://github.com/psf/requests/blob/v2.20.0/setup.py#L47

Therefore the change would not currently work. We would need to see if our code allows us to bump the requests version. But that might be difficult as we need to keep compatibility with python2. If you manage to upgrade requests that would be awesome 👍

2021-02-06 16:03 UTC, ReneNulschDE commented
Checked the same topic, let me try to dive deeper

2021-02-06 18:13 UTC, ReneNulschDE commented
Hi @stephanebruckert ,

I made some test with Requests 2.25 and six 1.15 under python 2.7.18 and at least the simple code examples running fine.

2021-02-09 08:42 UTC, stephanebruckert commented
@ReneNulschDE I will check ASAP, I need to run the integration tests manually

2021-02-27 15:43 UTC, merged

2021-02-28 23:06 UTC, stephanebruckert commented
Thanks for that @ReneNulschDE, merged & released!