Create TUTORIAL.md
plamere/spotipy pull request #823
Opened 2022-06-08 03:22 UTC by avivaschmitz

I have contributed a tutorial that walks a user through the steps necessary to set up Spotipy and start using it for the very first time to complete a simple task. The intended audience is new users and potential contributors who have little experience coding and no experience with the Spotify API. 

This tutorial is a necessary addition to Spotipy because there is very little existing documentation for brand new users. The [README.md](https://github.com/plamere/spotipy/blob/master/README.md) file contains installation instructions and a “Quick Start” section, but they are severely lacking in detail and are far from complete. For example, they don’t contain any information on how to connect Spotipy to your Spotify developer account, how to set up a Spotify app that is compatible with Spotipy, or how to use Spotipy to accomplish a basic task. The new tutorial that I have created covers all of this.

2022-06-15 08:00 UTC, Shide approved these changes
LGTM

2022-06-18 22:59 UTC, stephanebruckert requested changes
Can you add a link to TUTORIAL.md in the README?

https://github.com/plamere/spotipy/blob/master/README.md#reporting-issues

You could write:

> For common questions please check our [FAQ](FAQ.md) or [beginner tutorial](TUTORIAL.md).

2022-06-18 22:59 UTC, stephanebruckert commented on TUTORIAL.md
> +
please remove these empty lines

2022-10-29 13:21 UTC, stephanebruckert commented
I ended up merging https://github.com/plamere/spotipy/pull/872

2022-10-29 13:21 UTC, closed without merging